# Generated by Django 5.1.2 on 2024-11-09 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0005_nurse_wordboy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nurse',
            old_name='special',
            new_name='address',
        ),
    ]
