# Generated by Django 5.1.2 on 2024-11-10 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0006_rename_special_nurse_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wordboy',
            name='gender',
        ),
    ]
