# Generated by Django 5.1.2 on 2024-11-10 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0007_remove_wordboy_gender'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WordBoy',
            new_name='WardBoy',
        ),
    ]
